spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect

## did not work, use spring.jpa.hibernate.ddl-auto
#hibernate:
#  hbm2ddl:
#    auto: create

## enable gzip http response
server:
  compression:
    enabled: true