#logging.level.org.hibernate.SQL: DEBUG

spring:
  h2:
    console:
      enabled: true
      path: /h2 # 웹 DB UI URL
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
#    properties:
#      hibernate:
#        show-sql: true
#        format_sql: true
    hibernate:
      ddl-auto: update

## did not work, use spring.jpa.hibernate.ddl-auto
#hibernate:
#  show-sql: true
#  hbm2ddl:
#    auto: update

## enable gzip http response
server:
  compression:
    enabled: true